/pscratch/sd/b/brelypo/Predicting_SIC_SIE/NC_FILE_PROCESSING/patchify_utils.py:34: UserWarning: Warning for 'lon_spilldown': 213 cells were unassigned (patch ID -1) and will be excluded from the patch distribution plot.
  warnings.warn(
Exception in thread Thread-22 (_pin_memory_loop):
Traceback (most recent call last):
  File "/pscratch/sd/b/brelypo/conda_env/sic_sie_env/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/pscratch/sd/b/brelypo/conda_env/sic_sie_env/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/pscratch/sd/b/brelypo/conda_env/sic_sie_env/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 59, in _pin_memory_loop
    do_one_step()
  File "/pscratch/sd/b/brelypo/conda_env/sic_sie_env/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 35, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/pscratch/sd/b/brelypo/conda_env/sic_sie_env/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/pscratch/sd/b/brelypo/conda_env/sic_sie_env/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 541, in rebuild_storage_fd
    fd = df.detach()
  File "/pscratch/sd/b/brelypo/conda_env/sic_sie_env/lib/python3.10/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/pscratch/sd/b/brelypo/conda_env/sic_sie_env/lib/python3.10/multiprocessing/resource_sharer.py", line 86, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/pscratch/sd/b/brelypo/conda_env/sic_sie_env/lib/python3.10/multiprocessing/connection.py", line 508, in Client
    answer_challenge(c, authkey)
  File "/pscratch/sd/b/brelypo/conda_env/sic_sie_env/lib/python3.10/multiprocessing/connection.py", line 752, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/pscratch/sd/b/brelypo/conda_env/sic_sie_env/lib/python3.10/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/pscratch/sd/b/brelypo/conda_env/sic_sie_env/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/pscratch/sd/b/brelypo/conda_env/sic_sie_env/lib/python3.10/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
